import sqlmodel

"""initial

Revision ID: 13b22cb91f65
Revises: 
Create Date: 2024-12-29 13:58:01.733176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13b22cb91f65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrs_heroes',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('mage', 'assassin', 'warrior', 'priest', 'tank', name='hrs_role'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_hrs_heroes_uuid'), 'hrs_heroes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hrs_heroes_uuid'), table_name='hrs_heroes')
    op.drop_table('hrs_heroes')
    # ### end Alembic commands ###
